[project]
name = "test-update"
version = "1.0.0"
description = "Test app with auto update"
requires-python = ">=3.11"
dependencies = [
    "pyside6",
    "requests",
    "packaging"
]

[project.scripts]
app = "app.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"